#pragma once

#include "NiRefObject.hpp"
#include "NiPoint3.hpp"

class TESSound;

class TESAnimGroup : public NiRefObject {
public:
	TESAnimGroup();
	virtual ~TESAnimGroup();

	enum Type : UInt16 {
		Idle = 0x0,
		DynamicIdle,
		SpecialIdle,
		Forward,
		Backward,
		Left,
		Right,
		FastForward,
		FastBackward,
		FastLeft,
		FastRight,
		DodgeForward,
		DodgeBack,
		DodgeLeft,
		DodgeRight,
		TurnLeft,
		TurnRight,
		Aim,
		AimUp,
		AimDown,
		AimIS,
		AimISUp,
		AimISDown,
		Holster,
		Equip,
		Unequip,
		AttackLeft,
		AttackLeftUp,
		AttackLeftDown,
		AttackLeftIS,
		AttackLeftISUp,
		AttackLeftISDown,
		AttackRight,
		AttackRightUp,
		AttackRightDown,
		AttackRightIS,
		AttackRightISUp,
		AttackRightISDown,
		Attack3,
		Attack3Up,
		Attack3Down,
		Attack3IS,
		Attack3ISUp,
		Attack3ISDown,
		Attack4,
		Attack4Up,
		Attack4Down,
		Attack4IS,
		Attack4ISUp,
		Attack4ISDown,
		Attack5,
		Attack5Up,
		Attack5Down,
		Attack5IS,
		Attack5ISUp,
		Attack5ISDown,
		Attack6,
		Attack6Up,
		Attack6Down,
		Attack6IS,
		Attack6ISUp,
		Attack6ISDown,
		Attack7,
		Attack7Up,
		Attack7Down,
		Attack7IS,
		Attack7ISUp,
		Attack7ISDown,
		Attack8,
		Attack8Up,
		Attack8Down,
		Attack8IS,
		Attack8ISUp,
		Attack8ISDown,
		AttackLoop,
		AttackLoopUp,
		AttackLoopDown,
		AttackLoopIS,
		AttackLoopISUp,
		AttackLoopISDown,
		AttackSpin,
		AttackSpinUp,
		AttackSpinDown,
		AttackSpinIS,
		AttackSpinISUp,
		AttackSpinISDown,
		AttackSpin2,
		AttackSpin2Up,
		AttackSpin2Down,
		AttackSpin2IS,
		AttackSpin2ISUp,
		AttackSpin2ISDown,
		AttackPower,
		AttackForwardPower,
		AttackBackPower,
		AttackLeftPower,
		AttackRightPower,
		AttackCustom1Power,
		AttackCustom2Power,
		AttackCustom3Power,
		AttackCustom4Power,
		AttackCustom5Power,
		PlaceMine,
		PlaceMineUp,
		PlaceMineDown,
		PlaceMineIS,
		PlaceMineISUp,
		PlaceMineISDown,
		PlaceMine2,
		PlaceMine2Up,
		PlaceMine2Down,
		PlaceMine2IS,
		PlaceMine2ISUp,
		PlaceMine2ISDown,
		AttackThrow,
		AttackThrowUp,
		AttackThrowDown,
		AttackThrowIS,
		AttackThrowISUp,
		AttackThrowISDown,
		AttackThrow2,
		AttackThrow2Up,
		AttackThrow2Down,
		AttackThrow2IS,
		AttackThrow2ISUp,
		AttackThrow2ISDown,
		AttackThrow3,
		AttackThrow3Up,
		AttackThrow3Down,
		AttackThrow3IS,
		AttackThrow3ISUp,
		AttackThrow3ISDown,
		AttackThrow4,
		AttackThrow4Up,
		AttackThrow4Down,
		AttackThrow4IS,
		AttackThrow4ISUp,
		AttackThrow4ISDown,
		AttackThrow5,
		AttackThrow5Up,
		AttackThrow5Down,
		AttackThrow5IS,
		AttackThrow5ISUp,
		AttackThrow5ISDown,
		Attack9,
		Attack9Up,
		Attack9Down,
		Attack9IS,
		Attack9ISUp,
		Attack9ISDown,
		AttackThrow6,
		AttackThrow6Up,
		AttackThrow6Down,
		AttackThrow6IS,
		AttackThrow6ISUp,
		AttackThrow6ISDown,
		AttackThrow7,
		AttackThrow7Up,
		AttackThrow7Down,
		AttackThrow7IS,
		AttackThrow7ISUp,
		AttackThrow7ISDown,
		AttackThrow8,
		AttackThrow8Up,
		AttackThrow8Down,
		AttackThrow8IS,
		AttackThrow8ISUp,
		AttackThrow8ISDown,
		Counter,
		stomp,
		BlockIdle,
		BlockHit,
		Recoil,
		ReloadWStart,
		ReloadXStart,
		ReloadYStart,
		ReloadZStart,
		ReloadA,
		ReloadB,
		ReloadC,
		ReloadD,
		ReloadE,
		ReloadF,
		ReloadG,
		ReloadH,
		ReloadI,
		ReloadJ,
		ReloadK,
		ReloadL,
		ReloadM,
		ReloadN,
		ReloadO,
		ReloadP,
		ReloadQ,
		ReloadR,
		ReloadS,
		ReloadW,
		ReloadX,
		ReloadY,
		ReloadZ,
		JamA,
		JamB,
		JamC,
		JamD,
		JamE,
		JamF,
		JamG,
		JamH,
		JamI,
		JamJ,
		JamK,
		JamL,
		JamM,
		JamN,
		JamO,
		JamP,
		JamQ,
		JamR,
		JamS,
		JamW,
		JamX,
		JamY,
		JamZ,
		Stagger,
		Death,
		Talking,
		PipBoy,
		JumpStart,
		JumpLoop,
		JumpLand,
		HandGrip1,
		HandGrip2,
		HandGrip3,
		HandGrip4,
		HandGrip5,
		HandGrip6,
		JumpLoopForward,
		JumpLoopBackward,
		JumpLoopLeft,
		JumpLoopRight,
		PipBoyChild,
		JumpLandForward,
		JumpLandBackward,
		JumpLandLeft,
		JumpLandRight,

		Max,
		None = 0xFF
	};

	struct AnimGroupInfo {
		const char* pcName;
		UInt8		ucSequenceType;
		UInt8		pad[3];
		UInt32		unk08[7];
	};

	struct AnimGroupSound {
		float		unk00;
		UInt8		ucSoundID;
		float		fSpeedMult;
		TESSound*	pSound;
	};

	UInt8			ucPriorities[8];
	UInt16			usGroupID;
	UInt8			unk12;
	UInt32			uiNumKeys;
	float*			pfKeyTimes;
	NiPoint3		kMoveVector;
	bool			bLeftOrRight_whichFootToSwitch;
	bool			bBlend;
	bool			bBlendIn;
	bool			bBlendOut;
	bool			bDecal;
	const char*		pcParentNodeName;
	UInt32			uiSoundCount;
	AnimGroupSound* pSounds;

	Type GetSequenceType() const;

	double GetMoveVectorMagnitude() const;

	bool IsMovemementSequence() const;
};

ASSERT_SIZE(TESAnimGroup, 0x3C);
ASSERT_SIZE(TESAnimGroup::AnimGroupSound, 0x10);